name: curved_progress_bar
description: Progressbar that has curved edge and can add animation duration to build the progressbar.
version: 1.0.2
homepage: https://github.com/uttam-laila/curved_progress_bar.git

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0